show_task_route:
  path: /tasks/{task}
  controller: App\Controller\TaskController::show
  methods: GET

create_task_route:
  path: /tasks
  controller: App\Controller\TaskController::create
  methods: POST
