foo_route:
  path:     /foo
  controller: App\Controller\FooController::index
  methods:    GET

foo_placeholder_route:
  path:     /foo/{id}
  controller: App\Controller\FooController::load
  methods:    GET