foo_route:
  path: /tasks/{task}
  controller: App\Controller\TaskController::show
  methods: GET

foo_placeholder_route:
  path: /tasks
  controller: App\Controller\TaskController::create
  methods: POST
